/**
 * This class is generated by jOOQ
 */
package org.lxh.useradmin.entity;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.lxh.useradmin.entity.tables.Department;
import org.lxh.useradmin.entity.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kostream extends SchemaImpl {

    private static final long serialVersionUID = 652517056;

    /**
     * The reference instance of <code>kostream</code>
     */
    public static final Kostream KOSTREAM = new Kostream();

    /**
     * The table <code>kostream.department</code>.
     */
    public final Department DEPARTMENT = org.lxh.useradmin.entity.tables.Department.DEPARTMENT;

    /**
     * The table <code>kostream.user</code>.
     */
    public final User USER = org.lxh.useradmin.entity.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Kostream() {
        super("kostream", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Department.DEPARTMENT,
            User.USER);
    }
}
