/**
 * This class is generated by jOOQ
 */
package org.lxh.useradmin.entity;


import javax.annotation.Generated;

import org.lxh.useradmin.entity.tables.Department;
import org.lxh.useradmin.entity.tables.User;


/**
 * Convenience access to all tables in kostream
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kostream.department</code>.
     */
    public static final Department DEPARTMENT = org.lxh.useradmin.entity.tables.Department.DEPARTMENT;

    /**
     * The table <code>kostream.user</code>.
     */
    public static final User USER = org.lxh.useradmin.entity.tables.User.USER;
}
